# Prod inventory file for Ansible

[rhel:children]
rhel-dockers

[rhel-dockers:children]
rhel-docker-master
rhel-docker-workers

[rhel-docker-master]
twittix-1 ansible_host=192.168.5.1 ansible_ssh_host=192.168.5.1

[rhel-docker-workers]
twittix-2 ansible_host=192.168.5.2 ansible_ssh_host=192.168.5.2

[monitoring]
monitoring-oob ansible_host=192.168.5.3 ansible_ssh_host=192.168.5.3
