[home:children]
webservers
dockers

[skeleton]
debian-12 ansible_ssh_host=192.168.1.26 ansible_ssh_port=22 ansible_ssh_user='root'

[dockers]
twittix-1 ansible_ssh_host=192.168.1.25 ansible_ssh_port=22 ansible_ssh_user='root'
twittix-2 ansible_ssh_host=192.168.1.28 ansible_ssh_port=22 ansible_ssh_user='root'

[monitoring]
monitoring-oob ansible_ssh_host=192.168.1.27 ansible_ssh_port=22 ansible_ssh_user='root'