#SPDX-License-Identifier: MIT-0
---
# handlers file for install-docker-rhel

- name: start docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  
- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted