---
- hosts: webservers
  become: true
  vars:

    virtualhosts_root_dir: /var/www/virtualhosts
    directory_index: "index.php index.html"
    virtualhosts:
      - server_name: example.internal
        server_admin: "moi"
      - server_name: truc.internal
        server_admin: "moi"
  roles:
    - ../../roles/deb-setup
    - ../../roles/apache-webserver-setup
    - ../../roles/apache-virtualhosts-setup