#SPDX-License-Identifier: MIT-0
---
# tasks file for ssh-setup

- name: Set up SSH authorized keys
  ansible.builtin.authorized_key:
    user: "{{ ansible_ssh_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  loop: "{{ ssh_authorized_keys }}"
