---
- name: Configure Firewall on Docker Swarm Master
  hosts: rhel-docker-master
  become: true
  vars:
    ansible_ssh_user: alma
    ansible_ssh_port: 22
  tasks:
    - include_tasks: ../../roles/firewall/tasks/docker-master.yml

- name: Configure Firewall on Docker Swarm Workers
  hosts: rhel-docker-workers
  become: true
  vars:
    ansible_ssh_user: alma
    ansible_ssh_port: 22
  tasks:
    - include_tasks: ../../roles/firewall/tasks/docker-worker.yml