#SPDX-License-Identifier: MIT-0
---
# tasks file for docker masters firewall 

- name: Set interface eth0 to dmz zone
  ansible.posix.firewalld:
    interface: eth0
    zone: dmz
    permanent: yes
    state: enabled
  become: yes
  
- name: Set eth1 and eth2 to internal zone
  ansible.posix.firewalld:
    interface: "{{ item }}"
    zone: internal
    permanent: yes
    state: enabled
  loop:
    - eth1
    - eth2
  become: yes

- name: Set NetworkManager zone for eth0 (dmz)
  community.general.nmcli:
    conn_name: "System eth0"
    zone: dmz
    state: present
  become: yes

- name: Set NetworkManager zone for eth1 and eth2 (internal)
  community.general.nmcli:
    conn_name: "System {{ item }}"
    zone: internal
    state: present
  loop:
    - eth1
    - eth2
  become: yes

- name: Open port 22/tcp in firewalld (zone dmz)
  ansible.posix.firewalld:
    port: 22/tcp
    zone: dmz
    permanent: yes
    state: enabled
    immediate: yes
  become: yes

- name: Open port 80/tcp in firewalld (zone dmz)
  ansible.posix.firewalld:
    port: 80/tcp
    zone: dmz
    permanent: yes
    state: enabled
    immediate: yes
  become: yes

- name: Open port 443/tcp in firewalld (zone dmz)
  ansible.posix.firewalld:
    port: 443/tcp
    zone: dmz
    permanent: yes
    state: enabled
    immediate: yes
  become: yes

- name: Open port 8080/tcp in firewalld (zone dmz)
  ansible.posix.firewalld:
    port: 8080/tcp
    zone: dmz
    permanent: yes
    state: enabled
    immediate: yes
  become: yes

- name: Open port 8000/tcp in firewalld (zone dmz)
  ansible.posix.firewalld:
    port: 8000/tcp
    zone: dmz
    permanent: yes
    state: enabled
    immediate: yes
  become: yes

- name: Open port 5173/tcp in firewalld (zone dmz)
  ansible.posix.firewalld:
    port: 5173/tcp
    zone: dmz
    permanent: yes
    state: enabled
    immediate: yes
  become: yes

- name: Open port 2377/tcp in firewalld (zone internal)
  ansible.posix.firewalld:
    port: 2377/tcp
    zone: internal
    permanent: yes
    state: enabled
    immediate: yes
  become: yes

- name: Open port 7946/tcp in firewalld (zone internal)
  ansible.posix.firewalld:
    port: 7946/tcp
    zone: internal
    permanent: yes
    state: enabled
    immediate: yes
  become: yes

- name: Open port 4789/udp in firewalld (zone internal)
  ansible.posix.firewalld:
    port: 4789/udp
    zone: internal
    permanent: yes
    state: enabled
    immediate: yes
  notify: restart firewalld
  become: yes

- name: Open port 6556/tcp in firewalld (zone internal)
  ansible.posix.firewalld:
    port: 6556/tcp
    zone: internal
    permanent: yes
    state: enabled
    immediate: yes
  become: yes
