#SPDX-License-Identifier: MIT-0
---
# tasks file for install-docker

- name: Download Docker GPG key and add it to the keyring
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: yes

- name: Add Docker GPG key to apt keyring
  ansible.builtin.apt_key:
    file: /etc/apt/keyrings/docker.asc
    state: present
  become: yes

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    filename: docker.list
    repo: "{{ apt_repository }}"
    state: present
  become: yes

- name: Remove obsolete Docker packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ obsolete_packages }}"
  when: obsolete_packages is defined
  become: yes

- name: Update apt and Install Docker engine
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ packages_list }}"
  become: yes