#SPDX-License-Identifier: MIT-0
---
# tasks file for apache-setup

- name: Download the Sury PHP keyring
  ansible.builtin.get_url:
    url: "{{ url_keyring }}"
    dest: /tmp/php-archive-keyring.deb

- name: Install the Sury PHP keyring
  ansible.builtin.apt:
    deb: /tmp/php-archive-keyring.deb
    state: present

- name: Add Sury PHP repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/php.list
    line: "deb [signed-by=/usr/share/keyrings/debsuryorg-archive-keyring.gpg] {{ php_sury_repo }} {{ ansible_lsb.codename }} main"
    create: yes

# Install Apache and php8.4 packages
- name: Install Apache and PHP packages
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_php_packages }}"
  notify:
    - start apache2 
    - enable apache2

# Copy PHP index file in /var/www/html
- name: Copy PHP test file
  ansible.builtin.copy:
    src: index.php
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: '0644'

# Remove default Apache index.html
- name: Remove default Apache index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

# Add DirectoryIndex to Apache default configuration
- name: Add DirectoryIndex to Apache default configuration
  ansible.builtin.lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    insertafter: '^\s*DocumentRoot '
    line: '        DirectoryIndex index.php index.html'
    regexp: '^\s*DirectoryIndex '
    backup: yes
  notify: reload apache2
