---
- hosts: rhel-dockers
  become: true
  vars:
    ansible_ssh_user: alma
    ansible_ssh_port: 22
  roles:
    - ../../roles/rhel-setup
    - ../../roles/install-docker-rhel

- hosts: rhel-docker-master
  become: true
  vars:
    ansible_ssh_user: alma
    ansible_ssh_port: 22
  tasks:
    - import_tasks: ../../roles/install-docker-deb/tasks/init-swarm.yml

- hosts: rhel-docker-workers
  become: true
  vars:
    ansible_ssh_user: alma
    ansible_ssh_port: 22
    master_ip: "{{ hostvars['twittix-1'].ansible_ssh_host }}"
  tasks:
    - import_tasks: ../../roles/install-docker-deb/tasks/join-cluster.yml